<?php

$FACTORY_CONFIG = [
    'farm' => [
        'tier' => 1,
        'name' => 'Farm',
        'input' => [['resource' => 'money', 'amount' => 9]],
        'output' => [['resource' => 'food', 'amount' => 3]],
        'construction_cost' => [['resource' => 'money', 'amount' => 500]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 30,
        'gp_value' => 1
    ],
    'windmill' => [
        'tier' => 1,
        'name' => 'Windmill',
        'input' => [['resource' => 'money', 'amount' => 1]],
        'output' => [['resource' => 'power', 'amount' => 1]],
        'construction_cost' => [['resource' => 'money', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 30,
        'gp_value' => 1
    ],
    'quarry' => [
        'tier' => 1,
        'name' => 'Quarry',
        'input' => [['resource' => 'money', 'amount' => 10]],
        'output' => [['resource' => 'building_materials', 'amount' => 1]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000]],
        'land' => ['type' => 'mountain', 'amount' => 5],
        'construction_time' => 30,
        'gp_value' => 1
    ],
    'sandstone_quarry' => [
        'tier' => 1,
        'name' => 'Sandstone Quarry',
        'input' => [['resource' => 'money', 'amount' => 10]],
        'output' => [['resource' => 'building_materials', 'amount' => 1]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000]],
        'land' => ['type' => 'desert', 'amount' => 5],
        'construction_time' => 30,
        'gp_value' => 1
    ],
    'sawmill' => [
        'tier' => 1,
        'name' => 'Sawmill',
        'input' => [['resource' => 'money', 'amount' => 10]],
        'output' => [['resource' => 'building_materials', 'amount' => 1]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000]],
        'land' => ['type' => 'forest', 'amount' => 5],
        'construction_time' => 30,
        'gp_value' => 1
    ],
    'ciderworks' => [
        'tier' => 1,
        'name' => 'Ciderworks',
        'input' => [['resource' => 'money', 'amount' => 4],
                    ['resource' => 'power', 'amount' => 12]],
        'output' => [['resource' => 'consumer_goods', 'amount' => 2]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250],
                                ['resource' => 'apple_tree', 'amount' => 5]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 60,
        'gp_value' => 2
    ],
    'sandy_soda_factory' => [
        'tier' => 1,
        'name' => 'Sandy Soda Factory',
        'input' => [['resource' => 'money', 'amount' => 4],
                    ['resource' => 'power', 'amount' => 12]],
        'output' => [['resource' => 'consumer_goods', 'amount' => 2]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250],
                                ['resource' => 'cactus', 'amount' => 5]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 60,
        'gp_value' => 2
    ],
    'silk_factory' => [
        'tier' => 1,
        'name' => 'Silk Factory',
        'input' => [['resource' => 'money', 'amount' => 4],
                    ['resource' => 'power', 'amount' => 12]],
        'output' => [['resource' => 'consumer_goods', 'amount' => 2]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250],
                                ['resource' => 'mulberry', 'amount' => 5]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 60,
        'gp_value' => 2
    ],
    'beekeeper' => [
        'tier' => 1,
        'name' => 'Beekeeper',
        'input' => [['resource' => 'money', 'amount' => 4],
                    ['resource' => 'power', 'amount' => 12],
                    ['resource' => 'beehive', 'amount' => 1]],
        'output' => [['resource' => 'consumer_goods', 'amount' => 2]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 60,
        'gp_value' => 2
    ],
    'goat_shepherd' => [
        'tier' => 1,
        'name' => 'Goat Shepherd',
        'input' => [['resource' => 'money', 'amount' => 2],
                    ['resource' => 'power', 'amount' => 10],
                    ['resource' => 'goat', 'amount' => 1]],
        'output' => [['resource' => 'food', 'amount' => 1],
                     ['resource' => 'consumer_goods', 'amount' => 1]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 60,
        'gp_value' => 2
    ],
    'clam_divers' => [
        'tier' => 1,
        'name' => 'Clam Divers',
        'input' => [['resource' => 'money', 'amount' => 4],
                    ['resource' => 'power', 'amount' => 5],
                    ['resource' => 'clam', 'amount' => 1]],
        'output' => [['resource' => 'food', 'amount' => 5]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 1],
        'construction_time' => 60,
        'gp_value' => 2
    ],
    'shrimp_trawler' => [
        'tier' => 1,
        'name' => 'Shrimp Trawler',
        'input' => [['resource' => 'money', 'amount' => 4],
                    ['resource' => 'power', 'amount' => 5],
                    ['resource' => 'shrimp', 'amount' => 1]],
        'output' => [['resource' => 'food', 'amount' => 2]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 1],
        'construction_time' => 60,
        'gp_value' => 2
    ],
    'coal_power_plant' => [
        'tier' => 1,
        'name' => 'Coal Power Plant',
        'input' => [['resource' => 'money', 'amount' => 1],
                    ['resource' => 'coal', 'amount' => 1]],
        'output' => [['resource' => 'power', 'amount' => 7]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 60,
        'gp_value' => 2
    ],
    'iron_smelter' => [
        'tier' => 1,
        'name' => 'Iron Smelter',
        'input' => [['resource' => 'money', 'amount' => 57],
                    ['resource' => 'power', 'amount' => 68],
                    ['resource' => 'iron', 'amount' => 1]],
        'output' => [['resource' => 'metal', 'amount' => 1]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 60,
        'gp_value' => 2
    ],
    'stonemason' => [
        'tier' => 1,
        'name' => 'Stone Mason',
        'input' => [['resource' => 'money', 'amount' => 4],
                    ['resource' => 'power', 'amount' => 5],
                    ['resource' => 'marble', 'amount' => 1]],
        'output' => [['resource' => 'building_materials', 'amount' => 1],
                     ['resource' => 'consumer_goods', 'amount' => 1]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 60,
        'gp_value' => 2
    ],
];
