<?php

$FACTORY_CONFIG = [
    'farm' => [
        'tier' => 1,
        'name' => 'Farm',
        'input' => [['resource' => 'money', 'amount' => 9]],
        'output' => [['resource' => 'food', 'amount' => 3]],
        'construction_cost' => [['resource' => 'money', 'amount' => 500]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 30,
        'gp_value' => 1
    ],
    'windmill' => [
        'tier' => 1,
        'name' => 'Windmill',
        'input' => [['resource' => 'money', 'amount' => 5]],
        'output' => [['resource' => 'power', 'amount' => 5]],
        'construction_cost' => [['resource' => 'money', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 30,
        'gp_value' => 1
    ],
    'quarry' => [
        'tier' => 1,
        'name' => 'Quarry',
        'input' => [['resource' => 'money', 'amount' => 27]],
        'output' => [['resource' => 'building_materials', 'amount' => 3]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000]],
        'land' => ['type' => 'mountain', 'amount' => 5],
        'construction_time' => 30,
        'gp_value' => 1
    ],
    'sandstone_quarry' => [
        'tier' => 1,
        'name' => 'Sandstone Quarry',
        'input' => [['resource' => 'money', 'amount' => 27]],
        'output' => [['resource' => 'building_materials', 'amount' => 3]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000]],
        'land' => ['type' => 'desert', 'amount' => 5],
        'construction_time' => 30,
        'gp_value' => 1
    ],
    'sawmill' => [
        'tier' => 1,
        'name' => 'Sawmill',
            'input' => [['resource' => 'money', 'amount' => 27]],
        'output' => [['resource' => 'building_materials', 'amount' => 3]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000]],
        'land' => ['type' => 'forest', 'amount' => 5],
        'construction_time' => 30,
        'gp_value' => 1
    ],
    'jungle_sawmill' => [
        'tier' => 1,
        'name' => 'Jungle Sawmill',
            'input' => [['resource' => 'money', 'amount' => 27]],
        'output' => [['resource' => 'building_materials', 'amount' => 3]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000]],
        'land' => ['type' => 'jungle', 'amount' => 5],
        'construction_time' => 30,
        'gp_value' => 1
    ],
    'concrete_factory' => [
        'tier' => 1,
        'name' => 'Concrete Factory',
        'input' => [['resource' => 'money', 'amount' => 27]],
        'output' => [['resource' => 'building_materials', 'amount' => 3]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000]],
        'land' => ['type' => 'cleared_land', 'amount' => 10],
        'construction_time' => 30,
        'gp_value' => 1
    ],
    'stationery_factory' => [
        'tier' => 1,
        'name' => 'Stationery Factory',
        'input' => [['resource' => 'money', 'amount' => 3],
                    ['resource' => 'power', 'amount' => 13]],
        'output' => [['resource' => 'consumer_goods', 'amount' => 1]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 60,
        'gp_value' => 1
    ],
    'ciderworks' => [
        'tier' => 1,
        'name' => 'Ciderworks',
        'input' => [['resource' => 'money', 'amount' => 11],
                    ['resource' => 'power', 'amount' => 11]],
        'output' => [['resource' => 'consumer_goods', 'amount' => 2]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250],
                                ['resource' => 'apple_tree', 'amount' => 5]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 60,
        'gp_value' => 2
    ],
    'sandy_soda_factory' => [
        'tier' => 1,
        'name' => 'Sandy Soda Factory',
        'input' => [['resource' => 'money', 'amount' => 11],
                    ['resource' => 'power', 'amount' => 11]],
        'output' => [['resource' => 'consumer_goods', 'amount' => 2]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250],
                                ['resource' => 'cactus', 'amount' => 5]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 60,
        'gp_value' => 2
    ],
    'silk_factory' => [
        'tier' => 1,
        'name' => 'Fancy Uniform Factory',
        'input' => [['resource' => 'money', 'amount' => 11],
                    ['resource' => 'power', 'amount' => 11]],
        'output' => [['resource' => 'consumer_goods', 'amount' => 2]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250],
                                ['resource' => 'mulberry', 'amount' => 5]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 60,
        'gp_value' => 2
    ],
    'beekeeper' => [
        'tier' => 1,
        'name' => 'Beekeeper',
        'input' => [['resource' => 'money', 'amount' => 11],
                    ['resource' => 'power', 'amount' => 11],
                    ['resource' => 'beehive', 'amount' => 1]],
        'output' => [['resource' => 'consumer_goods', 'amount' => 2]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 60,
        'gp_value' => 2
    ],
    'goat_shepherd' => [
        'tier' => 1,
        'name' => 'Goat Shepherd',
        'input' => [['resource' => 'money', 'amount' => 2],
                    ['resource' => 'power', 'amount' => 9],
                    ['resource' => 'goat', 'amount' => 1]],
        'output' => [['resource' => 'food', 'amount' => 1],
                     ['resource' => 'consumer_goods', 'amount' => 1]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 60,
        'gp_value' => 2
    ],
    'clam_divers' => [
        'tier' => 1,
        'name' => 'Clam Divers',
        'input' => [['resource' => 'money', 'amount' => 4],
                    ['resource' => 'power', 'amount' => 5],
                    ['resource' => 'clam', 'amount' => 1]],
        'output' => [['resource' => 'food', 'amount' => 5]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 1],
        'construction_time' => 60,
        'gp_value' => 2
    ],
    'shrimp_trawler' => [
        'tier' => 1,
        'name' => 'Shrimp Trawler',
        'input' => [['resource' => 'money', 'amount' => 4],
                    ['resource' => 'power', 'amount' => 5],
                    ['resource' => 'shrimp', 'amount' => 1]],
        'output' => [['resource' => 'food', 'amount' => 5]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 1],
        'construction_time' => 60,
        'gp_value' => 2
    ],
    'coal_power_plant' => [
        'tier' => 1,
        'name' => 'Coal Power Plant',
        'input' => [['resource' => 'money', 'amount' => 12],
                    ['resource' => 'coal', 'amount' => 1]],
        'output' => [['resource' => 'power', 'amount' => 20]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 60,
        'gp_value' => 2
    ],
    'iron_smelter' => [
        'tier' => 1,
        'name' => 'Iron Smelter',
        'input' => [['resource' => 'money', 'amount' => 6],
                    ['resource' => 'power', 'amount' => 7],
                    ['resource' => 'iron', 'amount' => 1]],
        'output' => [['resource' => 'metal', 'amount' => 1]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 60,
        'gp_value' => 2
    ],
    'stonemason' => [
        'tier' => 1,
        'name' => 'Stone Mason',
        'input' => [['resource' => 'money', 'amount' => 9],
                    ['resource' => 'power', 'amount' => 8],
                    ['resource' => 'marble', 'amount' => 1]],
        'output' => [['resource' => 'building_materials', 'amount' => 1],
                     ['resource' => 'consumer_goods', 'amount' => 1]],
        'construction_cost' => [['resource' => 'money', 'amount' => 1000],
                                ['resource' => 'building_materials', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 5],
        'construction_time' => 60,
        'gp_value' => 2
    ],
    'hydro_plant' => [
        'tier' => 2,
        'name' => 'Hydro Plant',
        'input' => [['resource' => 'money', 'amount' => 7]],
        'output' => [['resource' => 'power', 'amount' => 10]],
        'construction_cost' => [['resource' => 'money', 'amount' => 5000],
                               ['resource' => 'building_materials', 'amount' => 500],
                               ['resource' => 'metal', 'amount' => 100]],
        'land' => ['type' => 'river', 'amount' => 5],
        'construction_time' => 180,
        'gp_value' => 4
    ],
    'hydro_dam' => [
        'tier' => 2,
        'name' => 'Hydro Dam',
        'input' => [['resource' => 'money', 'amount' => 7]],
        'output' => [['resource' => 'power', 'amount' => 10]],
        'construction_cost' => [['resource' => 'money', 'amount' => 5000],
                               ['resource' => 'building_materials', 'amount' => 500],
                               ['resource' => 'metal', 'amount' => 100]],
        'land' => ['type' => 'lake', 'amount' => 5],
        'construction_time' => 180,
        'gp_value' => 4
    ],
    'coffee_plantation' => [
        'tier' => 2,
        'name' => 'Coffee Plantation',
        'input' => [['resource' => 'money', 'amount' => 23],
                    ['resource' => 'power', 'amount' => 23]],
        'output' => [['resource' => 'consumer_goods', 'amount' => 5]],
        'construction_cost' => [['resource' => 'money', 'amount' => 5000],
                               ['resource' => 'building_materials', 'amount' => 500],
                               ['resource' => 'metal', 'amount' => 100],
                               ['resource' => 'coffea', 'amount' => 5]],
        'land' => ['type' => 'cleared_land', 'amount' => 10],
        'construction_time' => 180,
        'gp_value' => 4
    ],
    'pharmacy' => [
        'tier' => 2,
        'name' => 'Pharmacy',
        'input' => [['resource' => 'money', 'amount' => 23],
                    ['resource' => 'power', 'amount' => 23]],
        'output' => [['resource' => 'consumer_goods', 'amount' => 5]],
        'construction_cost' => [['resource' => 'money', 'amount' => 5000],
                               ['resource' => 'building_materials', 'amount' => 500],
                               ['resource' => 'metal', 'amount' => 100],
                               ['resource' => 'herbs', 'amount' => 5]],
        'land' => ['type' => 'cleared_land', 'amount' => 10],
        'construction_time' => 180,
        'gp_value' => 4
    ],
    'tobacco_plantation' => [
        'tier' => 2,
        'name' => 'Tobacco Plantation',
        'input' => [['resource' => 'money', 'amount' => 23],
                    ['resource' => 'power', 'amount' => 23]],
        'output' => [['resource' => 'consumer_goods', 'amount' => 5]],
        'construction_cost' => [['resource' => 'money', 'amount' => 5000],
                               ['resource' => 'building_materials', 'amount' => 500],
                               ['resource' => 'metal', 'amount' => 100],
                               ['resource' => 'tobacco_plant', 'amount' => 5]],
        'land' => ['type' => 'cleared_land', 'amount' => 10],
        'construction_time' => 180,
        'gp_value' => 4
    ],
    'dairy_farm' => [
        'tier' => 2,
        'name' => 'Dairy Farm',
        'input' => [['resource' => 'money', 'amount' => 6],
                    ['resource' => 'power', 'amount' => 7],
                    ['resource' => 'cow', 'amount' => 1]],
        'output' => [['resource' => 'food', 'amount' => 10]],
        'construction_cost' => [['resource' => 'money', 'amount' => 5000],
                               ['resource' => 'building_materials', 'amount' => 500],
                               ['resource' => 'metal', 'amount' => 100]],
        'land' => ['type' => 'cleared_land', 'amount' => 10],
        'construction_time' => 180,
        'gp_value' => 4
    ],
    'clothing_factory' => [
        'tier' => 2,
        'name' => 'Clothing Factory',
        'input' => [['resource' => 'money', 'amount' => 23],
                    ['resource' => 'power', 'amount' => 23],
                    ['resource' => 'sheep', 'amount' => 1]],
        'output' => [['resource' => 'consumer_goods', 'amount' => 5]],
        'construction_cost' => [['resource' => 'money', 'amount' => 5000],
                               ['resource' => 'building_materials', 'amount' => 500],
                               ['resource' => 'metal', 'amount' => 100]],
        'land' => ['type' => 'cleared_land', 'amount' => 10],
        'construction_time' => 180,
        'gp_value' => 4
    ],
    'bass_fishery' => [
        'tier' => 2,
        'name' => 'Bass Fishery',
        'input' => [['resource' => 'money', 'amount' => 6],
                    ['resource' => 'power', 'amount' => 7],
                    ['resource' => 'bass', 'amount' => 1]],
        'output' => [['resource' => 'food', 'amount' => 10]],
        'construction_cost' => [['resource' => 'money', 'amount' => 5000],
                               ['resource' => 'building_materials', 'amount' => 1000],
                               ['resource' => 'metal', 'amount' => 100]],
        'land' => ['type' => 'cleared_land', 'amount' => 1],
        'construction_time' => 180,
        'gp_value' => 4
    ],
    'cod_fishery' => [
        'tier' => 2,
        'name' => 'Cod Fishery',
        'input' => [['resource' => 'money', 'amount' => 6],
                    ['resource' => 'power', 'amount' => 7],
                    ['resource' => 'cod', 'amount' => 1]],
        'output' => [['resource' => 'food', 'amount' => 10]],
        'construction_cost' => [['resource' => 'money', 'amount' => 5000],
                               ['resource' => 'building_materials', 'amount' => 1000],
                               ['resource' => 'metal', 'amount' => 100]],
        'land' => ['type' => 'cleared_land', 'amount' => 1],
        'construction_time' => 180,
        'gp_value' => 4
    ],
    'aluminum_plant' => [
        'tier' => 2,
        'name' => 'Aluminum Plant',
        'input' => [['resource' => 'money', 'amount' => 25],
                    ['resource' => 'power', 'amount' => 36],
                    ['resource' => 'bauxite', 'amount' => 1]],
        'output' => [['resource' => 'building_materials', 'amount' => 5],
                     ['resource' => 'metal', 'amount' => 2]],
        'construction_cost' => [['resource' => 'money', 'amount' => 5000],
                               ['resource' => 'building_materials', 'amount' => 500]],
        'land' => ['type' => 'cleared_land', 'amount' => 10],
        'construction_time' => 180,
        'gp_value' => 4
    ],
    'electrical_engineering_supply_factory' => [
        'tier' => 2,
        'name' => 'Electrical Engineering Supply Factory',
        'input' => [['resource' => 'money', 'amount' => 7],
                    ['resource' => 'power', 'amount' => 10],
                    ['resource' => 'copper', 'amount' => 1]],
        'output' => [['resource' => 'metal', 'amount' => 2]],
        'construction_cost' => [['resource' => 'money', 'amount' => 5000],
                               ['resource' => 'building_materials', 'amount' => 500]],
        'land' => ['type' => 'cleared_land', 'amount' => 10],
        'construction_time' => 180,
        'gp_value' => 4
    ],
    'battery_assembler' => [
        'tier' => 2,
        'name' => 'Battery Assembler',
        'input' => [['resource' => 'money', 'amount' => 26],
                    ['resource' => 'power', 'amount' => 36],
                    ['resource' => 'lead', 'amount' => 1]],
        'output' => [['resource' => 'consumer_goods', 'amount' => 4],
                     ['resource' => 'metal', 'amount' => 2]],
        'construction_cost' => [['resource' => 'money', 'amount' => 5000],
                               ['resource' => 'building_materials', 'amount' => 500]],
        'land' => ['type' => 'cleared_land', 'amount' => 10],
        'construction_time' => 180,
        'gp_value' => 4
    ],
    'cotton_plantation' => [
        'tier' => 3,
        'name' => 'Cotton Plantation',
        'input' => [['resource' => 'money', 'amount' => 34],
                    ['resource' => 'power', 'amount' => 39]],
        'output' => [['resource' => 'consumer_goods', 'amount' => 10]],
        'construction_cost' => [['resource' => 'money', 'amount' => 10000],
                               ['resource' => 'building_materials', 'amount' => 2000],
                               ['resource' => 'metal', 'amount' => 250],
                               ['resource' => 'cotton', 'amount' => 5]],
        'land' => ['type' => 'cleared_land', 'amount' => 10],
        'construction_time' => 480,
        'gp_value' => 6
    ],
    'oak_mill' => [
        'tier' => 3,
        'name' => 'Oak Mill',
        'input' => [['resource' => 'money', 'amount' => 18],
                    ['resource' => 'power', 'amount' => 41]],
        'output' => [['resource' => 'building_materials', 'amount' => 15]],
        'construction_cost' => [['resource' => 'money', 'amount' => 10000],
                               ['resource' => 'building_materials', 'amount' => 2000],
                               ['resource' => 'metal', 'amount' => 250],
                               ['resource' => 'oak_tree', 'amount' => 5]],
        'land' => ['type' => 'cleared_land', 'amount' => 10],
        'construction_time' => 480,
        'gp_value' => 6
    ],
    'rubber_band_factory' => [
        'tier' => 3,
        'name' => 'Rubber Band Factory',
        'input' => [['resource' => 'money', 'amount' => 34],
                    ['resource' => 'power', 'amount' => 39]],
        'output' => [['resource' => 'consumer_goods', 'amount' => 10]],
        'construction_cost' => [['resource' => 'money', 'amount' => 10000],
                               ['resource' => 'building_materials', 'amount' => 2000],
                               ['resource' => 'metal', 'amount' => 250],
                               ['resource' => 'rubber_tree', 'amount' => 5]],
        'land' => ['type' => 'cleared_land', 'amount' => 10],
        'construction_time' => 480,
        'gp_value' => 6
    ],
    'hunting_lodge' => [
        'tier' => 3,
        'name' => 'Hunting Lodge',
        'input' => [['resource' => 'money', 'amount' => 52],
                    ['resource' => 'power', 'amount' => 13],
                    ['resource' => 'boar', 'amount' => 1]],
        'output' => [['resource' => 'consumer_goods', 'amount' => 5],
                     ['resource' => 'food', 'amount' => 10]],
        'construction_cost' => [['resource' => 'money', 'amount' => 10000],
                               ['resource' => 'building_materials', 'amount' => 2000],
                               ['resource' => 'metal', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 10],
        'construction_time' => 480,
        'gp_value' => 6
    ],
    'yak_farm' => [
        'tier' => 3,
        'name' => 'Yak Farm',
        'input' => [['resource' => 'money', 'amount' => 52],
                    ['resource' => 'power', 'amount' => 13],
                    ['resource' => 'yak', 'amount' => 1]],
        'output' => [['resource' => 'consumer_goods', 'amount' => 5],
                     ['resource' => 'food', 'amount' => 10]],
        'construction_cost' => [['resource' => 'money', 'amount' => 10000],
                               ['resource' => 'building_materials', 'amount' => 2000],
                               ['resource' => 'metal', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 10],
        'construction_time' => 480,
        'gp_value' => 6
    ],
    'mackerel_fishery' => [
        'tier' => 3,
        'name' => 'Mackerel Fishery',
        'input' => [['resource' => 'money', 'amount' => 6],
                    ['resource' => 'power', 'amount' => 12],
                    ['resource' => 'mackerel', 'amount' => 1]],
        'output' => [['resource' => 'food', 'amount' => 15]],
        'construction_cost' => [['resource' => 'money', 'amount' => 10000],
                               ['resource' => 'building_materials', 'amount' => 2000],
                               ['resource' => 'metal', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 10],
        'construction_time' => 480,
        'gp_value' => 6
    ],
    'salmon_fishery' => [
        'tier' => 3,
        'name' => 'Salmon Fishery',
        'input' => [['resource' => 'money', 'amount' => 6],
                    ['resource' => 'power', 'amount' => 12],
                    ['resource' => 'salmon', 'amount' => 1]],
        'output' => [['resource' => 'food', 'amount' => 15]],
        'construction_cost' => [['resource' => 'money', 'amount' => 10000],
                               ['resource' => 'building_materials', 'amount' => 2000],
                               ['resource' => 'metal', 'amount' => 250]],
        'land' => ['type' => 'cleared_land', 'amount' => 10],
        'construction_time' => 480,
        'gp_value' => 6
    ],
    'gold_mine' => [
        'tier' => 3,
        'name' => 'Gold Mine',
        'input' => [['resource' => 'power', 'amount' => 20],
                    ['resource' => 'gold', 'amount' => 1]],
        'output' => [['resource' => 'money', 'amount' => 90]],
        'construction_cost' => [['resource' => 'money', 'amount' => 10000],
                               ['resource' => 'building_materials', 'amount' => 2000]],
        'land' => ['type' => 'cleared_land', 'amount' => 10],
        'construction_time' => 480,
        'gp_value' => 6
    ],
    'platinum_refinery' => [
        'tier' => 3,
        'name' => 'Platinum Refinery',
        'input' => [['resource' => 'money', 'amount' => 10],
                    ['resource' => 'power', 'amount' => 15],
                    ['resource' => 'platinum', 'amount' => 1]],
        'output' => [['resource' => 'metal', 'amount' => 5]],
        'construction_cost' => [['resource' => 'money', 'amount' => 10000],
                               ['resource' => 'building_materials', 'amount' => 2000]],
        'land' => ['type' => 'cleared_land', 'amount' => 10],
        'construction_time' => 480,
        'gp_value' => 6
    ],
    'silver_mine' => [
        'tier' => 3,
        'name' => 'Silver Mine',
        'input' => [['resource' => 'power', 'amount' => 25],
                    ['resource' => 'silver', 'amount' => 1]],
        'output' => [['resource' => 'money', 'amount' => 100]],
        'construction_cost' => [['resource' => 'money', 'amount' => 10000],
                               ['resource' => 'building_materials', 'amount' => 2000]],
        'land' => ['type' => 'cleared_land', 'amount' => 10],
        'construction_time' => 480,
        'gp_value' => 6
    ],
];
