<?php

$LEVEL_CONFIG = [
    1 => 0,
    2 => 100,
    3 => 150,
    4 => 250,
    5 => 300,
    6 => 500,
    7 => 750,
    8 => 1250,
    9 => 2000,
    10 => 3000,
    11 => 5000,
    12 => 8000,
    13 => 13000,
    14 => 21000,
    15 => 34000
];



$UNIT_CONFIG = [
    'infantry' => [
        'name' => 'Infantry',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 1, 'food' => 1],
        'recruitable' => true,
        'special_abilities' => [],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 1000],
        'buffs' => [],
    ],
    'national_guard' => [
        'name' => 'National Guard',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 2,
        'armour' => 1,
        'maneuver' => 1,
        'hp' => 50,
        'upkeep' => ['food' => 1],
        'recruitable' => true,
        'special_abilities' => ['x2 all combat stats while defending'],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 500],
        'buffs' => [
            [
                "description" => "x2 all combat stats while defending",
                "buff_type" => "AllStatsMultiplier",
                "value" => 2,
                "target" => "IsDefending",
            ]
        ],
    ],
    'medic' => [
        'name' => 'Medic',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 1,
        'armour' => 1,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 1],
        'recruitable' => true,
        'special_abilities' => ['Reduces damage to friendly infantry units by 25% (max 2 per division)'],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 1500],
        'buffs' => [
            [
                "description" => "Reduces damage to friendly infantry units by 25%",
                "buff_type" => "FriendlyDamageReductionMultiplier",
                "value" => 0.75,
                "target" => "Infantry",
            ]
        ],
    ],
    'rioter' => [
        'name' => 'Rioter',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 1,
        'armour' => 1,
        'maneuver' => 1,
        'hp' => 40,
        'upkeep' => [],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 0],
        'buffs' => [],
    ],
    'mg_infantry' => [
        'name' => 'MG Infantry',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 6,
        'armour' => 1,
        'maneuver' => 1,
        'hp' => 50,
        'upkeep' => ['money' => 2, 'food' => 1],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 2500],
        'buffs' => [],
    ],
    'ak47_infantry' => [
        'name' => 'AK-47 Infantry',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 1, 'food' => 1],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 1000],
        'buffs' => [],
    ],
    'coast_guard' => [
        'name' => 'Coast Guard',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 6,
        'hp' => 50,
        'upkeep' => ['money' => 1, 'food' => 1],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 2500],
        'buffs' => [],
    ],
    'mobster' => [
        'name' => 'Mobster',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 4,
        'armour' => 1,
        'maneuver' => 1,
        'hp' => 50,
        'upkeep' => ['money' => 2, 'food' => 1],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 2000],
        'buffs' => [],
    ],
    'desert_fox_bodyguard' => [
        'name' => 'Desert Fox Bodyguard',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 2,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 2, 'food' => 1],
        'recruitable' => false,
        'special_abilities' => ['1.33x all combat stats in Zaheria'],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 3000],
        'buffs' => [
            [
                "description" => "1.33x all combat stats in Zaheria",
                "buff_type" => "AllStatsMultiplier",
                "value" => 1.34,
                "target" => "zaheria",
            ]
        ],
    ],
    'black_horn' => [
        'name' => 'Black Horn',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 4,
        'armour' => 1,
        'maneuver' => 4,
        'hp' => 50,
        'upkeep' => ['money' => 1, 'food' => 2],
        'recruitable' => false,
        'special_abilities' => ['1.33x all combat stats in Amarino'],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 3000],
        'buffs' => [
            [
                "description" => "1.33x all combat stats in Amarino",
                "buff_type" => "AllStatsMultiplier",
                "value" => 1.34,
                "target" => "amarino",
            ]
        ],
    ],
    'horseback_infantry' => [
        'name' => 'Horseback Infantry',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 5,
        'hp' => 50,
        'upkeep' => ['money' => 2, 'food' => 2],
        'recruitable' => false,
        'special_abilities' => ['1.33x all combat stats in San Sebastian'],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 3000],
        'buffs' => [
            [
                "description" => "1.33x all combat stats in San Sebastian",
                "buff_type" => "AllStatsMultiplier",
                "value" => 1.34,
                "target" => "san_sebastian",
            ]
        ],
    ],
    'arctic_camo_expert' => [
        'name' => 'Arctic Camoflauge Expert',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 3,
        'hp' => 50,
        'upkeep' => ['money' => 1, 'food' => 1],
        'recruitable' => false,
        'special_abilities' => ['4x maneuver in Tind'],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 3000],
        'buffs' => [
            [
                "description" => "4x maneuver in Tind",
                "buff_type" => "ManeuverMultiplier",
                "value" => 4,
                "target" => "tind",
            ]
        ],
    ],
    'forest_camo_expert' => [
        'name' => 'Forest Camoflauge Expert',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 3,
        'hp' => 50,
        'upkeep' => ['money' => 1, 'food' => 1],
        'recruitable' => false,
        'special_abilities' => ['4x maneuver in Westberg'],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 3000],
        'buffs' => [
            [
                "description" => "4x maneuver in Westberg",
                "buff_type" => "ManeuverMultiplier",
                "value" => 4,
                "target" => "westberg",
            ]
        ],
    ],
    'rpg_infantry' => [
        'name' => 'RPG Infantry',
        'tier' => 3,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 5, 'food' => 1],
        'recruitable' => false,
        'special_abilities' => ['4x firepower against armour units'],
        'building_requirements' => ['barracks' => 2], 
        'recruitment_time' => 180,
        'recruitment_cost' => ['money' => 3000],
        'buffs' => [
            [
                "description" => "4x firepower against armour units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Armour",
            ]
        ],
    ],
    'at4_infantry' => [
        'name' => 'AT4 Infantry',
        'tier' => 3,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 5, 'food' => 1],
        'recruitable' => true,
        'special_abilities' => ['4x firepower against armour units'],
        'building_requirements' => ['barracks' => 2], 
        'recruitment_time' => 180,
        'recruitment_cost' => ['money' => 3000],
        'buffs' => [
            [
                "description" => "4x firepower against armour units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Armour",
            ]
        ],
    ],
    'mortar_infantry' => [
        'name' => 'Mortar Infantry',
        'tier' => 4,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 5, 'food' => 1],
        'recruitable' => true,
        'special_abilities' => ['4x firepower against infantry units'],
        'building_requirements' => ['barracks' => 3], 
        'recruitment_time' => 480,
        'recruitment_cost' => ['money' => 5000],
        'buffs' => [
            [
                "description" => "4x firepower against infantry units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Infantry",
            ]
        ],
    ],
    'sniper' => [
        'name' => 'Sniper',
        'tier' => 4,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 5, 'food' => 1],
        'recruitable' => true,
        'special_abilities' => ['4x firepower against special forces units', '3x base roll multiplier'],
        'building_requirements' => ['barracks' => 3], 
        'recruitment_time' => 480,
        'recruitment_cost' => ['money' => 5000],
        'buffs' => [
            [
                "description" => "4x firepower against special forces units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Special Forces",
            ],
            [
                "description" => "3x base roll multiplier",
                "buff_type" => "BaseRollMultiplier",
                "value" => 3,
                "target" => "",
            ]
        ],
    ],
    'gear_infantry' => [
        'name' => 'GEAR Infantry',
        'tier' => 5,
        'type' => 'Infantry',
        'firepower' => 6,
        'armour' => 4,
        'maneuver' => 4,
        'hp' => 115,
        'upkeep' => ['money' => 5, 'food' => 3, 'ammunition' => 1],
        'recruitable' => true,
        'special_abilities' => [],
        'building_requirements' => ['barracks' => 4], 
        'recruitment_time' => 1440,
        'recruitment_cost' => ['money' => 10000],
        'buffs' => []
    ],
    'gear_sniper' => [
        'name' => 'GEAR Sniper',
        'tier' => 5,
        'type' => 'Infantry',
        'firepower' => 4,
        'armour' => 2,
        'maneuver' => 3,
        'hp' => 75,
        'upkeep' => ['money' => 5, 'food' => 3, 'ammunition' => 1],
        'recruitable' => true,
        'special_abilities' => ['4x firepower against special forces units', '3x base roll multiplier'],
        'building_requirements' => ['barracks' => 4], 
        'recruitment_time' => 1440,
        'recruitment_cost' => ['money' => 10000],
        'buffs' => [
            [
                "description" => "6x firepower against special forces units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 6,
                "target" => "Special Forces",
            ],
            [
                "description" => "3x base roll multiplier",
                "buff_type" => "BaseRollMultiplier",
                "value" => 3,
                "target" => "",
            ]
        ]
    ],
    'javelin_infantry' => [
        'name' => 'Javelin Infantry',
        'tier' => 5,
        'type' => 'Infantry',
        'firepower' => 4,
        'armour' => 2,
        'maneuver' => 3,
        'hp' => 75,
        'upkeep' => ['money' => 5, 'food' => 3, 'ammunition' => 1],
        'recruitable' => true,
        'special_abilities' => ['6x firepower against armour units'],
        'building_requirements' => ['barracks' => 4], 
        'recruitment_time' => 1440,
        'recruitment_cost' => ['money' => 10000],
        'buffs' => [
            [
                "description" => "6x firepower against armour units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 6,
                "target" => "Armour",
            ]
        ]
    ],
    'rocket_sniper' => [
        'name' => 'Rocket Sniper',
        'tier' => 6,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 5, 'food' => 1, 'ammunition' => 3],
        'recruitable' => true,
        'special_abilities' => ['4x firepower against armour units', '4x firepower against air units', '3x base roll multiplier'],
        'building_requirements' => ['barracks' => 5], 
        'recruitment_time' => 4320,
        'recruitment_cost' => ['money' => 25000],
        'buffs' => [
            [
                "description" => "4x firepower against armour units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Armour",
            ],
            [
                "description" => "4x firepower against air units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Air",
            ],
            [
                "description" => "3x base roll multiplier",
                "buff_type" => "BaseRollMultiplier",
                "value" => 3,
                "target" => "",
            ]
        ],
    ],
    'nuclear_rocket_sniper' => [
        'name' => 'Nuclear Rocket Sniper',
        'tier' => 11,
        'type' => 'Infantry',
        'firepower' => 4,
        'armour' => 2,
        'maneuver' => 3,
        'hp' => 75,
        'upkeep' => ['money' => 25, 'food' => 3, 'ammunition' => 10, 'uranium' => 1],
        'recruitable' => false,
        'special_abilities' => ['4x firepower against armour units', '4x firepower against air units', '3x base roll multiplier'],
        'building_requirements' => ['barracks' => 6], 
        'recruitment_time' => 4320,
        'recruitment_cost' => ['money' => 100000, 'uranium' => 500],
        'buffs' => [
            [
                "description" => "6x firepower against infantry units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Infantry",
            ],
            [
                "description" => "6x firepower against armour units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Armour",
            ],
            [
                "description" => "4x firepower against special forces units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Special Forces",
            ],
            [
                "description" => "6x firepower against air units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Air",
            ],
            [
                "description" => "3x base roll multiplier",
                "buff_type" => "BaseRollMultiplier",
                "value" => 3,
                "target" => "",
            ]
        ],
    ],
    'francesco_the_ace_of_spades' => [
        'name' => 'Francesco, the Ace of Spades',
        'tier' => 11,
        'type' => 'Infantry',
        'firepower' => 6,
        'armour' => 1,
        'maneuver' => 5,
        'hp' => 300,
        'upkeep' => ['money' => 500, 'food' => 1],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['barracks' => 6], 
        'recruitment_time' => 4320,
        'recruitment_cost' => ['money' => 10000],
        'buffs' => []
    ],
    'm1a1_abrahms' => [
        'name' => 'M1A1 Abrahms',
        'tier' => 4,
        'type' => 'Armour',
        'firepower' => 3,
        'armour' => 4,
        'maneuver' => 2,
        'hp' => 130,
        'upkeep' => ['money' => 15, 'fuel' => 1, 'ammunition' => 1],
        'recruitable' => true,
        'special_abilities' => [],
        'building_requirements' => ['heavy_armour_factory' => 1],
        'recruitment_time' => 1440,
        'recruitment_cost' => ['money' => 10000, 'metal' => 100],
        'buffs' => [],
    ],
    't72_tank' => [
        'name' => 'T-72 Tank',
        'tier' => 4,
        'type' => 'Armour',
        'firepower' => 3,
        'armour' => 4,
        'maneuver' => 2,
        'hp' => 130,
        'upkeep' => ['money' => 15, 'fuel' => 1, 'ammunition' => 1],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['heavy_armour_factory' => 1],
        'recruitment_time' => 1440,
        'recruitment_cost' => ['money' => 10000, 'metal' => 100],
        'buffs' => [],
    ],
    'm2_bradley' => [
        'name' => 'M2 Bradley',
        'tier' => 4,
        'type' => 'Armour',
        'firepower' => 2,
        'armour' => 3,
        'maneuver' => 2,
        'hp' => 85,
        'upkeep' => ['money' => 12, 'fuel' => 1, 'ammunition' => 1],
        'recruitable' => true,
        'special_abilities' => ['4x firepower against infantry units'],
        'building_requirements' => ['light_armour_factory' => 1],
        'recruitment_time' => 1440,
        'recruitment_cost' => ['money' => 7500, 'metal' => 100],
        'buffs' => [
            [
                "description" => "4x firepower against infantry units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Infantry",
            ]
        ],
    ],
    'secret_agent' => [
        'name' => 'Secret Agent',
        'tier' => 3,
        'type' => 'Special Forces',
        'firepower' => 4,
        'armour' => 2,
        'maneuver' => 3,
        'hp' => 50,
        'upkeep' => ['money' => 5],
        'recruitable' => false,
        'special_abilities' => ['1.5x firepower against infantry units'],
        'building_requirements' => ['special_forces_recruiting_agency' => 1],
        'recruitment_time' => 180, // 3 hours in minutes
        'recruitment_cost' => ['money' => 5000],
        'buffs' => [
            [
                "description" => "1.5x firepower against infantry units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 1.5,
                "target" => "Infantry",
            ]
        ],
    ],
    'sectopod' => [
        'name' => 'Sectopod',
        'tier' => 11,
        'type' => 'Armour',
        'firepower' => 10,
        'armour' => 10,
        'maneuver' => 11,
        'hp' => 300,
        'upkeep' => ['money' => 100000, 'fuel' => 5000, 'ammunition' => 25000],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['heavy_armour_factory' => 6],
        'recruitment_time' => 40320, // 672 hours (28 days) in minutes
        'recruitment_cost' => ['money' => 1000000000, 'metal' => 1000000],
        'buffs' => [],
    ],
    'sectoid' => [
        'name' => 'Sectoid',
        'tier' => 11,
        'type' => 'Special Forces',
        'firepower' => 8,
        'armour' => 8,
        'maneuver' => 9,
        'hp' => 50,
        'upkeep' => ['money' => 100000, 'ammunition' => 5000, 'food' => 25000],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['special_forces_recruiting_agency' => 1],
        'recruitment_time' => 40320,
        'recruitment_cost' => ['money' => 1000000000],
        'buffs' => [],
    ],
];

global $UNIT_CONFIG;