<?php

$LEVEL_CONFIG = [
    1 => 0,
    2 => 100,
    3 => 150,
    4 => 250,
    5 => 300,
    6 => 500,
    7 => 750,
    8 => 1250,
    9 => 2000,
    10 => 3000,
    11 => 5000,
    12 => 8000,
    13 => 13000,
    14 => 21000,
    15 => 34000
];



$UNIT_CONFIG = [
    'infantry' => [
        'name' => 'Infantry',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 1, 'food' => 1],
        'recruitable' => true,
        'special_abilities' => [],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 1000],
        'buffs' => [],
    ],
    'national_guard' => [
        'name' => 'National Guard',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 2,
        'armour' => 1,
        'maneuver' => 1,
        'hp' => 50,
        'upkeep' => ['food' => 1],
        'recruitable' => true,
        'special_abilities' => ['x2 all combat stats while defending'],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 500],
        'buffs' => [
            [
                "description" => "x2 all combat stats while defending",
                "buff_type" => "AllStatsMultiplier",
                "value" => 2,
                "target" => "IsDefending",
            ]
        ],
    ],
    'medic' => [
        'name' => 'Medic',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 1,
        'armour' => 1,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 1],
        'recruitable' => true,
        'special_abilities' => ['Reduces damage to friendly infantry units by 25% (max 2 per division)'],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 1500],
        'buffs' => [
            [
                "description" => "Reduces damage to friendly infantry units by 25%",
                "buff_type" => "FriendlyDamageReductionMultiplier",
                "value" => 0.75,
                "target" => "Infantry",
            ]
        ],
    ],
    'rioter' => [
        'name' => 'Rioter',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 1,
        'armour' => 1,
        'maneuver' => 1,
        'hp' => 40,
        'upkeep' => [],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 0],
        'buffs' => [],
    ],
    'mg_infantry' => [
        'name' => 'MG Infantry',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 6,
        'armour' => 1,
        'maneuver' => 1,
        'hp' => 50,
        'upkeep' => ['money' => 2, 'food' => 1],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 2500],
        'buffs' => [],
    ],
    'ak47_infantry' => [
        'name' => 'AK-47 Infantry',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 1, 'food' => 1],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 1000],
        'buffs' => [],
    ],
    'coast_guard' => [
        'name' => 'Coast Guard',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 6,
        'hp' => 50,
        'upkeep' => ['money' => 1, 'food' => 1],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 2500],
        'buffs' => [],
    ],
    'mobster' => [
        'name' => 'Mobster',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 4,
        'armour' => 1,
        'maneuver' => 1,
        'hp' => 50,
        'upkeep' => ['money' => 2, 'food' => 1],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 2000],
        'buffs' => [],
    ],
    'desert_fox_bodyguard' => [
        'name' => 'Desert Fox Bodyguard',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 2,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 2, 'food' => 1],
        'recruitable' => false,
        'special_abilities' => ['1.33x all combat stats in Zaheria'],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 3000],
        'buffs' => [
            [
                "description" => "1.33x all combat stats in Zaheria",
                "buff_type" => "AllStatsMultiplier",
                "value" => 1.34,
                "target" => "zaheria",
            ]
        ],
    ],
    'black_horn' => [
        'name' => 'Black Horn',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 4,
        'armour' => 1,
        'maneuver' => 4,
        'hp' => 50,
        'upkeep' => ['money' => 1, 'food' => 2],
        'recruitable' => false,
        'special_abilities' => ['1.33x all combat stats in Amarino'],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 3000],
        'buffs' => [
            [
                "description" => "1.33x all combat stats in Amarino",
                "buff_type" => "AllStatsMultiplier",
                "value" => 1.34,
                "target" => "amarino",
            ]
        ],
    ],
    'horseback_infantry' => [
        'name' => 'Horseback Infantry',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 5,
        'hp' => 50,
        'upkeep' => ['money' => 2, 'food' => 2],
        'recruitable' => false,
        'special_abilities' => ['1.33x all combat stats in San Sebastian'],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 3000],
        'buffs' => [
            [
                "description" => "1.33x all combat stats in San Sebastian",
                "buff_type" => "AllStatsMultiplier",
                "value" => 1.34,
                "target" => "san_sebastian",
            ]
        ],
    ],
    'arctic_camo_expert' => [
        'name' => 'Arctic Camoflauge Expert',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 3,
        'hp' => 50,
        'upkeep' => ['money' => 1, 'food' => 1],
        'recruitable' => false,
        'special_abilities' => ['4x maneuver in Tind'],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 3000],
        'buffs' => [
            [
                "description" => "4x maneuver in Tind",
                "buff_type" => "ManeuverMultiplier",
                "value" => 4,
                "target" => "tind",
            ]
        ],
    ],
    'forest_camo_expert' => [
        'name' => 'Forest Camoflauge Expert',
        'tier' => 2,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 3,
        'hp' => 50,
        'upkeep' => ['money' => 1, 'food' => 1],
        'recruitable' => false,
        'special_abilities' => ['4x maneuver in Westberg'],
        'building_requirements' => ['barracks' => 1], 
        'recruitment_time' => 60,
        'recruitment_cost' => ['money' => 3000],
        'buffs' => [
            [
                "description" => "4x maneuver in Westberg",
                "buff_type" => "ManeuverMultiplier",
                "value" => 4,
                "target" => "westberg",
            ]
        ],
    ],
    'rpg_infantry' => [
        'name' => 'RPG Infantry',
        'tier' => 3,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 5, 'food' => 1],
        'recruitable' => false,
        'special_abilities' => ['4x firepower against armour units'],
        'building_requirements' => ['barracks' => 2], 
        'recruitment_time' => 120,
        'recruitment_cost' => ['money' => 3000],
        'buffs' => [
            [
                "description" => "4x firepower against armour units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Armour",
            ]
        ],
    ],
    'at4_infantry' => [
        'name' => 'AT4 Infantry',
        'tier' => 3,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 5, 'food' => 1],
        'recruitable' => true,
        'special_abilities' => ['4x firepower against armour units'],
        'building_requirements' => ['barracks' => 2], 
        'recruitment_time' => 120,
        'recruitment_cost' => ['money' => 3000],
        'buffs' => [
            [
                "description" => "4x firepower against armour units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Armour",
            ]
        ],
    ],
    'mortar_infantry' => [
        'name' => 'Mortar Infantry',
        'tier' => 4,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 5, 'food' => 1],
        'recruitable' => true,
        'special_abilities' => ['4x firepower against infantry units'],
        'building_requirements' => ['barracks' => 3], 
        'recruitment_time' => 240,
        'recruitment_cost' => ['money' => 5000],
        'buffs' => [
            [
                "description" => "4x firepower against infantry units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Infantry",
            ]
        ],
    ],
    'sniper' => [
        'name' => 'Sniper',
        'tier' => 4,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 5, 'food' => 1],
        'recruitable' => true,
        'special_abilities' => ['4x firepower against special forces units', '3x base roll multiplier'],
        'building_requirements' => ['barracks' => 3], 
        'recruitment_time' => 240,
        'recruitment_cost' => ['money' => 5000],
        'buffs' => [
            [
                "description" => "4x firepower against special forces units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Special Forces",
            ],
            [
                "description" => "3x base roll multiplier",
                "buff_type" => "BaseRollMultiplier",
                "value" => 3,
                "target" => "",
            ]
        ],
    ],
    'gear_infantry' => [
        'name' => 'GEAR Infantry',
        'tier' => 5,
        'type' => 'Infantry',
        'firepower' => 6,
        'armour' => 4,
        'maneuver' => 4,
        'hp' => 115,
        'upkeep' => ['money' => 5, 'food' => 3, 'ammunition' => 1],
        'recruitable' => true,
        'special_abilities' => [],
        'building_requirements' => ['barracks' => 4], 
        'recruitment_time' => 360,
        'recruitment_cost' => ['money' => 10000],
        'buffs' => []
    ],
    'gear_sniper' => [
        'name' => 'GEAR Sniper',
        'tier' => 5,
        'type' => 'Infantry',
        'firepower' => 4,
        'armour' => 2,
        'maneuver' => 3,
        'hp' => 75,
        'upkeep' => ['money' => 5, 'food' => 3, 'ammunition' => 1],
        'recruitable' => true,
        'special_abilities' => ['6x firepower against special forces units', '3x base roll multiplier'],
        'building_requirements' => ['barracks' => 4], 
        'recruitment_time' => 360,
        'recruitment_cost' => ['money' => 10000],
        'buffs' => [
            [
                "description" => "6x firepower against special forces units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 6,
                "target" => "Special Forces",
            ],
            [
                "description" => "3x base roll multiplier",
                "buff_type" => "BaseRollMultiplier",
                "value" => 3,
                "target" => "",
            ]
        ]
    ],
    'javelin_infantry' => [
        'name' => 'Javelin Infantry',
        'tier' => 5,
        'type' => 'Infantry',
        'firepower' => 4,
        'armour' => 2,
        'maneuver' => 3,
        'hp' => 75,
        'upkeep' => ['money' => 5, 'food' => 3, 'ammunition' => 1],
        'recruitable' => true,
        'special_abilities' => ['6x firepower against armour units'],
        'building_requirements' => ['barracks' => 4], 
        'recruitment_time' => 360,
        'recruitment_cost' => ['money' => 10000],
        'buffs' => [
            [
                "description" => "6x firepower against armour units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 6,
                "target" => "Armour",
            ]
        ]
    ],
    'rocket_sniper' => [
        'name' => 'Rocket Sniper',
        'tier' => 6,
        'type' => 'Infantry',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 5, 'food' => 1, 'ammunition' => 3],
        'recruitable' => true,
        'special_abilities' => ['4x firepower against armour units', '4x firepower against air units', '3x base roll multiplier'],
        'building_requirements' => ['barracks' => 5], 
        'recruitment_time' => 720,
        'recruitment_cost' => ['money' => 25000],
        'buffs' => [
            [
                "description" => "4x firepower against armour units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Armour",
            ],
            [
                "description" => "4x firepower against air units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Air",
            ],
            [
                "description" => "3x base roll multiplier",
                "buff_type" => "BaseRollMultiplier",
                "value" => 3,
                "target" => "",
            ]
        ],
    ],
    'nuclear_rocket_sniper' => [
        'name' => 'Nuclear Rocket Sniper',
        'tier' => 11,
        'type' => 'Infantry',
        'firepower' => 4,
        'armour' => 2,
        'maneuver' => 3,
        'hp' => 75,
        'upkeep' => ['money' => 25, 'food' => 3, 'ammunition' => 10, 'uranium' => 1],
        'recruitable' => false,
        'special_abilities' => ['6x firepower against infantry units', '6x firepower against special forces units', '6x firepower against armour units', '6x firepower against air units', '3x base roll multiplier'],
        'building_requirements' => ['barracks' => 6], 
        'recruitment_time' => 4320,
        'recruitment_cost' => ['money' => 100000, 'uranium' => 500],
        'buffs' => [
            [
                "description" => "6x firepower against infantry units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Infantry",
            ],
            [
                "description" => "6x firepower against armour units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Armour",
            ],
            [
                "description" => "4x firepower against special forces units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Special Forces",
            ],
            [
                "description" => "6x firepower against air units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Air",
            ],
            [
                "description" => "3x base roll multiplier",
                "buff_type" => "BaseRollMultiplier",
                "value" => 3,
                "target" => "",
            ]
        ],
    ],
    'francesco_the_ace_of_spades' => [
        'name' => 'Francesco, the Ace of Spades',
        'tier' => 11,
        'type' => 'Infantry',
        'firepower' => 6,
        'armour' => 1,
        'maneuver' => 5,
        'hp' => 300,
        'upkeep' => ['money' => 500, 'food' => 1],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['barracks' => 6], 
        'recruitment_time' => 4320,
        'recruitment_cost' => ['money' => 10000],
        'buffs' => []
    ],
    'm1a1_abrahms' => [
        'name' => 'M1A1 Abrahms',
        'tier' => 5,
        'type' => 'Armour',
        'firepower' => 3,
        'armour' => 4,
        'maneuver' => 2,
        'hp' => 130,
        'upkeep' => ['money' => 15, 'fuel' => 1, 'ammunition' => 1],
        'recruitable' => true,
        'special_abilities' => [],
        'building_requirements' => ['heavy_armour_factory' => 1],
        'recruitment_time' => 360,
        'recruitment_cost' => ['money' => 10000, 'metal' => 100],
        'buffs' => [],
    ],
    't72_tank' => [
        'name' => 'T-72 Tank',
        'tier' => 5,
        'type' => 'Armour',
        'firepower' => 3,
        'armour' => 4,
        'maneuver' => 2,
        'hp' => 130,
        'upkeep' => ['money' => 15, 'fuel' => 1, 'ammunition' => 1],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['heavy_armour_factory' => 1],
        'recruitment_time' => 360,
        'recruitment_cost' => ['money' => 10000, 'metal' => 100],
        'buffs' => [],
    ],
    'humvee' => [
        'name' => 'Humvee',
        'tier' => 5,
        'type' => 'Armour',
        'firepower' => 2,
        'armour' => 2,
        'maneuver' => 4,
        'hp' => 75,
        'upkeep' => ['money' => 5, 'ammunition' => 1],
        'recruitable' => false,
        'special_abilities' => ['4x firepower against special forces units'],
        'building_requirements' => ['light_armour_factory' => 1],
        'recruitment_time' => 360,
        'recruitment_cost' => ['money' => 4000, 'metal' => 10],
        'buffs' => [
            [
                "description" => "4x firepower against special forces units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Special Forces",
            ],
        ],
    ],
    'technical' => [
        'name' => 'Technical',
        'tier' => 5,
        'type' => 'Armour',
        'firepower' => 3,
        'armour' => 2,
        'maneuver' => 3,
        'hp' => 75,
        'upkeep' => ['money' => 5, 'ammunition' => 1],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['light_armour_factory' => 1],
        'recruitment_time' => 360,
        'recruitment_cost' => ['money' => 4000, 'metal' => 10],
        'buffs' => [
            
        ],
    ],
    'bmp_1' => [
        'name' => 'BMP-1',
        'tier' => 5,
        'type' => 'Armour',
        'firepower' => 2,
        'armour' => 3,
        'maneuver' => 1,
        'hp' => 85,
        'upkeep' => ['money' => 10, 'fuel' => 1, 'ammunition' => 1],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['light_armour_factory' => 1],
        'recruitment_time' => 360,
        'recruitment_cost' => ['money' => 5000, 'metal' => 50],
        'buffs' => [],
    ],
    'armoured_limousine' => [
        'name' => 'Armoured Limousine',
        'tier' => 5,
        'type' => 'Armour',
        'firepower' => 2,
        'armour' => 3,
        'maneuver' => 3,
        'hp' => 85,
        'upkeep' => ['money' => 10],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['light_armour_factory' => 1],
        'recruitment_time' => 360,
        'recruitment_cost' => ['money' => 5000, 'metal' => 50],
        'buffs' => [],
    ],
    'armoured_combat_ambulance' => [
        'name' => 'Armoured Combat Ambulance',
        'tier' => 5,
        'type' => 'Armour',
        'firepower' => 1,
        'armour' => 3,
        'maneuver' => 3,
        'hp' => 85,
        'upkeep' => ['money' => 10, 'fuel' => 1],
        'recruitable' => true,
        'special_abilities' => ['Reduces damage to friendly special forces units by 25% (max 2 per division)'],
        'building_requirements' => ['light_armour_factory' => 1],
        'recruitment_time' => 360,
        'recruitment_cost' => ['money' => 5000, 'metal' => 50],
        'buffs' => [
            [
                "description" => "Reduces damage to friendly special forces units by 25%",
                "buff_type" => "FriendlyDamageReductionMultiplier",
                "value" => 0.75,
                "target" => "Special Forces",
            ]
        ],
    ],
    'k2_black_panther' => [
        'name' => 'K2 Black Panther',
        'tier' => 6,
        'type' => 'Armour',
        'firepower' => 3,
        'armour' => 2,
        'maneuver' => 1,
        'hp' => 115,
        'upkeep' => ['money' => 15, 'fuel' => 1, 'ammunition' => 1],
        'recruitable' => false,
        'special_abilities' => ["1.66x all combat stats in Zaheria"],
        'building_requirements' => ['heavy_armour_factory' => 2],
        'recruitment_time' => 720,
        'recruitment_cost' => ['money' => 10000, 'metal' => 100],
        'buffs' => [
            [
                "description" => "2x firepower against static units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 2,
                "target" => "Static",
            ],
        ],
    ],
    'm1a1_swift_desert_platoon' => [
        'name' => 'M1A1 Swift Desert Platoon',
        'tier' => 6,
        'type' => 'Armour',
        'firepower' => 3,
        'armour' => 4,
        'maneuver' => 2,
        'hp' => 130,
        'upkeep' => ['money' => 15, 'fuel' => 1, 'ammunition' => 1],
        'recruitable' => false,
        'special_abilities' => ["1.66x all combat stats in Zaheria"],
        'building_requirements' => ['heavy_armour_factory' => 2],
        'recruitment_time' => 720,
        'recruitment_cost' => ['money' => 10000, 'metal' => 100],
        'buffs' => [
            [
                "description" => "1.66x all combat stats in Zaheria",
                "buff_type" => "AllStatsMultiplier",
                "value" => 1.67,
                "target" => "zaheria",
            ]
        ],
    ],
    'leopard_2' => [
        'name' => 'Leopard 2',
        'tier' => 6,
        'type' => 'Armour',
        'firepower' => 3,
        'armour' => 4,
        'maneuver' => 2,
        'hp' => 130,
        'upkeep' => ['money' => 15, 'fuel' => 1, 'ammunition' => 1],
        'recruitable' => false,
        'special_abilities' => ["1.66x all combat stats in Tind"],
        'building_requirements' => ['heavy_armour_factory' => 2],
        'recruitment_time' => 720,
        'recruitment_cost' => ['money' => 10000, 'metal' => 100],
        'buffs' => [
            [
                "description" => "1.66x all combat stats in Tind",
                "buff_type" => "AllStatsMultiplier",
                "value" => 1.67,
                "target" => "tind",
            ]
        ],
    ],
    'stridsvagn_122' => [
        'name' => 'Stridsvagn 122',
        'tier' => 6,
        'type' => 'Armour',
        'firepower' => 3,
        'armour' => 4,
        'maneuver' => 2,
        'hp' => 130,
        'upkeep' => ['money' => 15, 'fuel' => 1, 'ammunition' => 1],
        'recruitable' => false,
        'special_abilities' => ["1.66x all combat stats in Westberg"],
        'building_requirements' => ['heavy_armour_factory' => 2],
        'recruitment_time' => 720,
        'recruitment_cost' => ['money' => 10000, 'metal' => 100],
        'buffs' => [
            [
                "description" => "1.66x all combat stats in Westberg",
                "buff_type" => "AllStatsMultiplier",
                "value" => 1.67,
                "target" => "westberg",
            ]
        ],
    ],
    'centurion_mk_5' => [
        'name' => 'Centurion Mk. 5',
        'tier' => 6,
        'type' => 'Armour',
        'firepower' => 3,
        'armour' => 4,
        'maneuver' => 2,
        'hp' => 130,
        'upkeep' => ['money' => 15, 'fuel' => 1, 'ammunition' => 1],
        'recruitable' => false,
        'special_abilities' => ["1.66x all combat stats in Amarino"],
        'building_requirements' => ['heavy_armour_factory' => 2],
        'recruitment_time' => 720,
        'recruitment_cost' => ['money' => 10000, 'metal' => 100],
        'buffs' => [
            [
                "description" => "1.66x all combat stats in Amarino",
                "buff_type" => "AllStatsMultiplier",
                "value" => 1.67,
                "target" => "amarino",
            ]
        ],
    ],
    'merkava_iv' => [
        'name' => 'Merkava IV',
        'tier' => 6,
        'type' => 'Armour',
        'firepower' => 3,
        'armour' => 4,
        'maneuver' => 2,
        'hp' => 130,
        'upkeep' => ['money' => 15, 'fuel' => 1, 'ammunition' => 1],
        'recruitable' => false,
        'special_abilities' => ["1.66x all combat stats in San Sebastian"],
        'building_requirements' => ['heavy_armour_factory' => 2],
        'recruitment_time' => 720,
        'recruitment_cost' => ['money' => 10000, 'metal' => 100],
        'buffs' => [
            [
                "description" => "1.66x all combat stats in San Sebastian",
                "buff_type" => "AllStatsMultiplier",
                "value" => 1.67,
                "target" => "san_sebastian",
            ]
        ],
    ],
    'm2_bradley' => [
        'name' => 'M2 Bradley',
        'tier' => 6,
        'type' => 'Armour',
        'firepower' => 2,
        'armour' => 3,
        'maneuver' => 2,
        'hp' => 85,
        'upkeep' => ['money' => 12, 'fuel' => 1, 'ammunition' => 1],
        'recruitable' => true,
        'special_abilities' => ['4x firepower against infantry units'],
        'building_requirements' => ['light_armour_factory' => 2],
        'recruitment_time' => 720,
        'recruitment_cost' => ['money' => 7500, 'metal' => 100],
        'buffs' => [
            [
                "description" => "4x firepower against infantry units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Infantry",
            ]
        ],
    ],
    'tank_destroyer' => [
        'name' => 'Tank Destroyer',
        'tier' => 7,
        'type' => 'Armour',
        'firepower' => 3,
        'armour' => 4,
        'maneuver' => 1,
        'hp' => 115,
        'upkeep' => ['money' => 25, 'fuel' => 3, 'ammunition' => 3],
        'recruitable' => true,
        'special_abilities' => ['4x firepower against armour units'],
        'building_requirements' => ['heavy_armour_factory' => 3],
        'recruitment_time' => 1440,
        'recruitment_cost' => ['money' => 15000, 'metal' => 250],
        'buffs' => [
            [
                "description" => "4x firepower against armour units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Armour",
            ]
        ],
    ],
    'volvo_repair_truck' => [
        'name' => 'Volvo Repair Truck',
        'tier' => 7,
        'type' => 'Armour',
        'firepower' => 1,
        'armour' => 2,
        'maneuver' => 3,
        'hp' => 85,
        'upkeep' => ['money' => 15, 'fuel' => 1],
        'recruitable' => true,
        'special_abilities' => ['Reduces damage to friendly armour units by 25% (max 2 per division)'],
        'building_requirements' => ['light_armour_factory' => 3],
        'recruitment_time' => 1440,
        'recruitment_cost' => ['money' => 10000, 'metal' => 100],
        'buffs' => [
            [
                "description" => "Reduces damage to friendly armour units by 25%",
                "buff_type" => "FriendlyDamageReductionMultiplier",
                "value" => 0.75,
                "target" => "Armour",
            ]
        ],
    ],
    'type_99a' => [
        'name' => 'Type 99A',
        'tier' => 8,
        'type' => 'Armour',
        'firepower' => 3,
        'armour' => 4,
        'maneuver' => 2,
        'hp' => 130,
        'upkeep' => ['money' => 30, 'fuel' => 5, 'ammunition' => 10],
        'recruitable' => true,
        'special_abilities' => ['4x firepower against static units'],
        'building_requirements' => ['heavy_armour_factory' => 4],
        'recruitment_time' => 2880,
        'recruitment_cost' => ['money' => 25000, 'metal' => 500],
        'buffs' => [
            [
                "description" => "4x firepower against static units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Static",
            ]
        ],
    ],
    '2k22_tunguska' => [
        'name' => '2K22 Tunguska',
        'tier' => 7,
        'type' => 'Armour',
        'firepower' => 3,
        'armour' => 2,
        'maneuver' => 3,
        'hp' => 100,
        'upkeep' => ['money' => 25, 'fuel' => 3, 'ammunition' => 3],
        'recruitable' => true,
        'special_abilities' => ['4x firepower against air units'],
        'building_requirements' => ['light_armour_factory' => 4],
        'recruitment_time' => 2880,
        'recruitment_cost' => ['money' => 15000, 'metal' => 250],
        'buffs' => [
            [
                "description" => "4x firepower against air units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Air",
            ]
        ],
    ],
    'gearhound_warhead' => [
        'name' => 'GEARHOUND Warhead',
        'tier' => 9,
        'type' => 'Armour',
        'firepower' => 7,
        'armour' => 7,
        'maneuver' => 4,
        'hp' => 245,
        'upkeep' => ['money' => 50, 'fuel' => 15, 'ammunition' => 15, 'uranium' => 3],
        'recruitable' => true,
        'special_abilities' => [],
        'building_requirements' => ['heavy_armour_factory' => 5],
        'recruitment_time' => 4320,
        'recruitment_cost' => ['money' => 50000, 'metal' => 1000],
        'buffs' => [
        ],
    ],
    'gearhound_shredder' => [
        'name' => 'GEARHOUND Shredder',
        'tier' => 9,
        'type' => 'Armour',
        'firepower' => 5,
        'armour' => 4,
        'maneuver' => 5,
        'hp' => 130,
        'upkeep' => ['money' => 18, 'fuel' => 5, 'ammunition' => 5],
        'recruitable' => true,
        'special_abilities' => ['6x firepower against infantry units'],
        'building_requirements' => ['light_armour_factory' => 5],
        'recruitment_time' => 4320,
        'recruitment_cost' => ['money' => 25000, 'metal' => 500],
        'buffs' => [
            [
                "description" => "6x firepower against infantry units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 6,
                "target" => "Infantry",
            ]
        ],
    ],
    'sectopod' => [
        'name' => 'Sectopod',
        'tier' => 11,
        'type' => 'Armour',
        'firepower' => 10,
        'armour' => 10,
        'maneuver' => 11,
        'hp' => 300,
        'upkeep' => ['money' => 100000, 'fuel' => 5000, 'ammunition' => 25000],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['heavy_armour_factory' => 6],
        'recruitment_time' => 40320,
        'recruitment_cost' => ['money' => 1000000000, 'metal' => 1000000],
        'buffs' => [],
    ],
    'trench_infantry' => [
        'name' => 'Trench Infantry',
        'tier' => 5,
        'type' => 'Static',
        'firepower' => 3,
        'armour' => 6,
        'maneuver' => 1,
        'hp' => 130,
        'upkeep' => ['money' => 5, 'ammunition' => 1],
        'recruitable' => true,
        'special_abilities' => ['6x firepower against infantry units'],
        'building_requirements' => ['engineer_lab' => 1],
        'recruitment_time' => 360,
        'recruitment_cost' => ['money' => 5000, 'building_materials' => 500],
        'buffs' => [
            [
                "description" => "6x firepower against infantry units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 6,
                "target" => "Infantry",
            ]
        ],
    ],
    'concrete_bunker' => [
        'name' => 'Concrete Bunker',
        'tier' => 6,
        'type' => 'Static',
        'firepower' => 2,
        'armour' => 8,
        'maneuver' => 1,
        'hp' => 540,
        'upkeep' => ['money' => 12, 'power' => 10, 'ammunition' => 3],
        'recruitable' => true,
        'special_abilities' => [],
        'building_requirements' => ['engineer_lab' => 2],
        'recruitment_time' => 720,
        'recruitment_cost' => ['money' => 25000, 'building_materials' => 2500, 'metal' => 500],
        'buffs' => [
        ],
    ],
    'zpu_4' => [
        'name' => 'ZPU-4',
        'tier' => 7,
        'type' => 'Static',
        'firepower' => 3,
        'armour' => 2,
        'maneuver' => 2,
        'hp' => 85,
        'upkeep' => ['money' => 24, 'ammunition' => 5],
        'recruitable' => true,
        'special_abilities' => ['6x firepower against air units'],
        'building_requirements' => ['engineer_lab' => 3],
        'recruitment_time' => 1440,
        'recruitment_cost' => ['money' => 10000],
        'buffs' => [
            [
                "description" => "6x firepower against air units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 6,
                "target" => "Air",
            ]
        ],
    ],
    'fortified_bunker' => [
        'name' => 'Fortified Bunker',
        'tier' => 8,
        'type' => 'Static',
        'firepower' => 3,
        'armour' => 10,
        'maneuver' => 1,
        'hp' => 1040,
        'upkeep' => ['money' => 25, 'power' => 20, 'ammunition' => 5],
        'recruitable' => true,
        'special_abilities' => [],
        'building_requirements' => ['engineer_lab' => 4],
        'recruitment_time' => 2880,
        'recruitment_cost' => ['money' => 100000, 'building_materials' => 10000, 'metal' => 2000],
        'buffs' => [
        ],
    ],
    'railgun' => [
        'name' => 'Railgun',
        'tier' => 9,
        'type' => 'Static',
        'firepower' => 20,
        'armour' => 4,
        'maneuver' => 2,
        'hp' => 150,
        'upkeep' => ['money' => 50, 'power' => 25, 'ammunition' => 20],
        'recruitable' => true,
        'special_abilities' => [],
        'building_requirements' => ['engineer_lab' => 5],
        'recruitment_time' => 4320,
        'recruitment_cost' => ['money' => 500000, 'building_materials' => 25000, 'metal' => 5000],
        'buffs' => [
        ],
    ],
    'f_35_lighting_ii' => [
        'name' => 'F-35 Lightning II',
        'tier' => 6,
        'type' => 'Air',
        'firepower' => 4,
        'armour' => 3,
        'maneuver' => 5,
        'hp' => 100,
        'upkeep' => ['money' => 16, 'fuel' => 2, 'ammunition' => 4],
        'recruitable' => true,
        'special_abilities' => [],
        'building_requirements' => ['airfield' => 1],
        'recruitment_time' => 720,
        'recruitment_cost' => ['money' => 10000, 'metal' => 100],
        'buffs' => [
        ],
    ],
    'sukhoi_su_75_checkmate' => [
        'name' => 'Sukhoi Su-75 Checkmate',
        'tier' => 6,
        'type' => 'Air',
        'firepower' => 4,
        'armour' => 3,
        'maneuver' => 5,
        'hp' => 100,
        'upkeep' => ['money' => 16, 'fuel' => 2, 'ammunition' => 4],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['airfield' => 1],
        'recruitment_time' => 720,
        'recruitment_cost' => ['money' => 10000, 'metal' => 100],
        'buffs' => [
        ],
    ],
    'mh_6_little_bird' => [
        'name' => 'MH-6 Little Bird',
        'tier' => 6,
        'type' => 'Air',
        'firepower' => 3,
        'armour' => 2,
        'maneuver' => 4,
        'hp' => 65,
        'upkeep' => ['money' => 10, 'fuel' => 1, 'ammunition' => 3],
        'recruitable' => true,
        'special_abilities' => ["4x firepower against special forces units"],
        'building_requirements' => ['airfield' => 1],
        'recruitment_time' => 720,
        'recruitment_cost' => ['money' => 5000, 'metal' => 25],
        'buffs' => [
            [
                "description" => "4x firepower against special forces units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Special Forces",
            ],
        ],
    ],
    'a10_thunderbolt' => [
        'name' => 'A10 Thunderbolt',
        'tier' => 7,
        'type' => 'Air',
        'firepower' => 3,
        'armour' => 3,
        'maneuver' => 4,
        'hp' => 80,
        'upkeep' => ['money' => 20, 'fuel' => 3, 'ammunition' => 5],
        'recruitable' => true,
        'special_abilities' => ["6x firepower against armour units"],
        'building_requirements' => ['airfield' => 2],
        'recruitment_time' => 1440,
        'recruitment_cost' => ['money' => 15000, 'metal' => 250],
        'buffs' => [
            [
                "description" => "6x firepower against armour units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 6,
                "target" => "Armour",
            ],
        ],
    ],
    'mq_9_reaper' => [
        'name' => 'MQ-9 Reaper',
        'tier' => 7,
        'type' => 'Air',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 3,
        'hp' => 45,
        'upkeep' => ['money' => 12, 'fuel' => 2, 'ammunition' => 6],
        'recruitable' => true,
        'special_abilities' => ["4x firepower against infantry units", "4x firepower against armour units"],
        'building_requirements' => ['airfield' => 2],
        'recruitment_time' => 1440,
        'recruitment_cost' => ['money' => 15000, 'metal' => 250],
        'buffs' => [
            [
                "description" => "4x firepower against infantry units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Infantry",
            ],
            [
                "description" => "4x firepower against armour units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Armour",
            ]
        ],
    ],
    'f_22_raptor' => [
        'name' => 'F-22 Raptor',
        'tier' => 8,
        'type' => 'Air',
        'firepower' => 4,
        'armour' => 3,
        'maneuver' => 5,
        'hp' => 100,
        'upkeep' => ['money' => 30, 'fuel' => 4, 'ammunition' => 10],
        'recruitable' => true,
        'special_abilities' => ["6x firepower against air units"],
        'building_requirements' => ['airfield' => 3],
        'recruitment_time' => 2880,
        'recruitment_cost' => ['money' => 25000, 'metal' => 500],
        'buffs' => [
            [
                "description" => "6x firepower against air units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 6,
                "target" => "Air",
            ],
        ],
    ],
    'pave_low' => [
        'name' => 'Pave Low',
        'tier' => 8,
        'type' => 'Air',
        'firepower' => 4,
        'armour' => 3,
        'maneuver' => 4,
        'hp' => 75,
        'upkeep' => ['money' => 10, 'fuel' => 3, 'ammunition' => 5],
        'recruitable' => true,
        'special_abilities' => ["6x firepower against special forces units"],
        'building_requirements' => ['airfield' => 3],
        'recruitment_time' => 2880,
        'recruitment_cost' => ['money' => 15000, 'metal' => 250],
        'buffs' => [
            [
                "description" => "6x firepower against special forces units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 6,
                "target" => "Special Forces",
            ],
        ],
    ],
    'mi_24_hind' => [
        'name' => 'MI-24 Hind',
        'tier' => 8,
        'type' => 'Air',
        'firepower' => 4,
        'armour' => 3,
        'maneuver' => 4,
        'hp' => 75,
        'upkeep' => ['money' => 10, 'fuel' => 3, 'ammunition' => 5],
        'recruitable' => false,
        'special_abilities' => ["6x firepower against special forces units"],
        'building_requirements' => ['airfield' => 3],
        'recruitment_time' => 2880,
        'recruitment_cost' => ['money' => 15000, 'metal' => 250],
        'buffs' => [
            [
                "description" => "6x firepower against special forces units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 6,
                "target" => "Special Forces",
            ],
        ],
    ],
    'b_2_spirit' => [
        'name' => 'B-2 Spirit',
        'tier' => 9,
        'type' => 'Air',
        'firepower' => 9,
        'armour' => 6,
        'maneuver' => 8,
        'hp' => 155,
        'upkeep' => ['money' => 40, 'fuel' => 12, 'ammunition' => 12, 'uranium' => 1],
        'recruitable' => true,
        'special_abilities' => [],
        'building_requirements' => ['airfield' => 4],
        'recruitment_time' => 4320,
        'recruitment_cost' => ['money' => 15000, 'metal' => 250],
        'buffs' => [
        ],
    ],
    'mq_20_avenger' => [
        'name' => 'MQ-20 Avenger',
        'tier' => 9,
        'type' => 'Air',
        'firepower' => 4,
        'armour' => 2,
        'maneuver' => 5,
        'hp' => 70,
        'upkeep' => ['money' => 25, 'fuel' => 3, 'ammunition' => 5],
        'recruitable' => true,
        'special_abilities' => ["6x firepower against infantry units", "6x firepower against armour units"],
        'building_requirements' => ['airfield' => 4],
        'recruitment_time' => 4320,
        'recruitment_cost' => ['money' => 20000, 'metal' => 500],
        'buffs' => [
            [
                "description" => "6x firepower against infantry units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 6,
                "target" => "Infantry",
            ],
            [
                "description" => "6x firepower against armour units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 6,
                "target" => "Armour",
            ]
        ],
    ],
    'lockheed_ac_130' => [
        'name' => 'Lockheed AC-130',
        'tier' => 10,
        'type' => 'Air',
        'firepower' => 3,
        'armour' => 2,
        'maneuver' => 11,
        'hp' => 130,
        'upkeep' => ['money' => 100, 'fuel' => 15, 'ammunition' => 15],
        'recruitable' => true,
        'special_abilities' => ["4x firepower against infantry units", "4x firepower against armour units", "4x firepower against special forces units", "4x maneuver multiplier to friendly units (max 1 per division)"],
        'building_requirements' => ['airfield' => 5],
        'recruitment_time' => 10080,
        'recruitment_cost' => ['money' => 100000, 'metal' => 1000],
        'buffs' => [
            [
                "description" => "4x firepower against infantry units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Infantry",
            ],
            [
                "description" => "4x firepower against armour units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Armour",
            ],
            [
                "description" => "4x firepower against special forces units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Special Forces",
            ],
            [
                "description" => "4x maneuver multiplier to friendly units",
                "buff_type" => "FriendlyManeuverMultiplier",
                "value" => 4,
                "target" => "All",
            ],
        ],
    ],
    'secret_agent' => [
        'name' => 'Secret Agent',
        'tier' => 3,
        'type' => 'Special Forces',
        'firepower' => 4,
        'armour' => 2,
        'maneuver' => 3,
        'hp' => 50,
        'upkeep' => ['money' => 5],
        'recruitable' => false,
        'special_abilities' => ['1.5x firepower against infantry units'],
        'building_requirements' => ['special_forces_recruiting_agency' => 1],
        'recruitment_time' => 180,
        'recruitment_cost' => ['money' => 5000],
        'buffs' => [
            [
                "description" => "1.5x firepower against infantry units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 1.5,
                "target" => "Infantry",
            ]
        ],
    ],
    'riot_cop' => [
        'name' => 'Riot Cop',
        'tier' => 3,
        'type' => 'Special Forces',
        'firepower' => 1,
        'armour' => 4,
        'maneuver' => 1,
        'hp' => 75,
        'upkeep' => ['money' => 5],
        'recruitable' => true,
        'special_abilities' => ['4x armour against infantry units'],
        'building_requirements' => ['special_forces_recruiting_agency' => 1],
        'recruitment_time' => 180,
        'recruitment_cost' => ['money' => 5000],
        'buffs' => [
            [
                "description" => "4x armour against infantry units",
                "buff_type" => "ArmourMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Infantry",
            ]
        ],
    ],
    'navy_seal' => [
        'name' => 'Navy SEAL',
        'tier' => 3,
        'type' => 'Special Forces',
        'firepower' => 4,
        'armour' => 2,
        'maneuver' => 3,
        'hp' => 50,
        'upkeep' => ['money' => 5],
        'recruitable' => false,
        'special_abilities' => ['1.5x firepower against infantry units'],
        'building_requirements' => ['special_forces_recruiting_agency' => 1],
        'recruitment_time' => 180,
        'recruitment_cost' => ['money' => 5000],
        'buffs' => [
            [
                "description" => "1.5x firepower against infantry units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 1.5,
                "target" => "Infantry",
            ]
        ],
    ],
    'k9_team' => [
        'name' => 'K9 Team',
        'tier' => 4,
        'type' => 'Special Forces',
        'firepower' => 1,
        'armour' => 1,
        'maneuver' => 6,
        'hp' => 50,
        'upkeep' => ['money' => 10, 'food' => 2],
        'recruitable' => true,
        'special_abilities' => ['4x firepower against infantry units'],
        'building_requirements' => ['special_forces_recruiting_agency' => 2],
        'recruitment_time' => 360,
        'recruitment_cost' => ['money' => 5000],
        'buffs' => [
            [
                "description" => "4x firepower against infantry units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Infantry",
            ]
        ],
    ],
    'combat_engineer' => [
        'name' => 'Combat Engineer',
        'tier' => 5,
        'type' => 'Special Forces',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 12, 'food' => 1, 'ammunition' => 1],
        'recruitable' => true,
        'special_abilities' => ['4x firepower against static units'],
        'building_requirements' => ['special_forces_recruiting_agency' => 3],
        'recruitment_time' => 720,
        'recruitment_cost' => ['money' => 15000],
        'buffs' => [
            [
                "description" => "4x firepower against static units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 4,
                "target" => "Static",
            ]
        ],
    ],
    'signals_jammer' => [
        'name' => 'Signals Jammer',
        'tier' => 6,
        'type' => 'Special Forces',
        'firepower' => 3,
        'armour' => 1,
        'maneuver' => 2,
        'hp' => 50,
        'upkeep' => ['money' => 15, 'food' => 1, 'power' => 15],
        'recruitable' => true,
        'special_abilities' => ['Reduces maneuver of enemy units by 25% (max 2 per division)'],
        'building_requirements' => ['special_forces_recruiting_agency' => 4],
        'recruitment_time' => 1440,
        'recruitment_cost' => ['money' => 25000],
        'buffs' => [
            [
                "description" => "Reduces maneuver of enemy units by 25%",
                "buff_type" => "EnemyManeuverMultiplier",
                "value" => 0.75,
                "target" => "All",
            ]
        ],
    ],
    'tyz_uav_engineer' => [
        'name' => 'TyZ UAV Engineer',
        'tier' => 7,
        'type' => 'Special Forces',
        'firepower' => 4,
        'armour' => 2,
        'maneuver' => 3,
        'hp' => 75,
        'upkeep' => ['money' => 20, 'food' => 1, 'power' => 15, 'fuel' => 5],
        'recruitable' => true,
        'special_abilities' => ['6x firepower against static units', 'Reduces damage to friendly static units by 25% (max 2 per division)'],
        'building_requirements' => ['special_forces_recruiting_agency' => 5],
        'recruitment_time' => 720,
        'recruitment_cost' => ['money' => 15000],
        'buffs' => [
            [
                "description" => "6x firepower against static units",
                "buff_type" => "FirepowerMultiplierAgainstUnit",
                "value" => 6,
                "target" => "Static",
            ],
            [
                "description" => "Reduces damage to friendly static units by 25%",
                "buff_type" => "FriendlyDamageReductionMultiplier",
                "value" => 0.75,
                "target" => "Static",
            ]
        ],
    ],
    'sectoid' => [
        'name' => 'Sectoid',
        'tier' => 11,
        'type' => 'Special Forces',
        'firepower' => 8,
        'armour' => 8,
        'maneuver' => 9,
        'hp' => 50,
        'upkeep' => ['money' => 100000, 'ammunition' => 5000, 'food' => 25000],
        'recruitable' => false,
        'special_abilities' => [],
        'building_requirements' => ['special_forces_recruiting_agency' => 6],
        'recruitment_time' => 40320,
        'recruitment_cost' => ['money' => 1000000000],
        'buffs' => [],
    ],
];

global $UNIT_CONFIG;